#!/bin/sh

TORRC=/opt/tor/torrc

export http_proxy=127.0.0.1:8888

cat $TORRC

# EXIT NODE LOCATION --------------------------------------------------------------------------------------------------

if [ -n "${EXIT_NODE}" ]
then
    sed -i 's/# \(ExitNodes \){US}/\1'$EXIT_NODE'/' $TORRC
    sed -i 's/# \(StrictNodes\)/\1/' $TORRC
fi

# EXIT NODE FILTER ----------------------------------------------------------------------------------------------------

if [ -n "${EXCLUDE_NODE}" ]
then
    sed -i 's/# \(ExcludeExitNodes \){RU}/\1'$EXCLUDE_NODE'/' $TORRC
    sed -i 's/# \(StrictNodes\)/\1/' $TORRC
fi

# # USE OWN WEBTUNEL BRIDGE --------------------------------------------------------------------------------------------
update_line="Bridge webtunnel 192.0.2.3:1 url=https://akbwadp9lc5fyyz0cj4d76z643pxgbfh6oyc-167-71-71-157.sslip.io/5m9yq0j4ghkz0fz7qmuw58cvbjon0ebnrsp0"

if [ -n "${BRIDGE}" ]
then
    sed -i "s^$update_line^Bridge $BRIDGE^" $TORRC
fi

# NODE ROTATION -------------------------------------------------------------------------------------------------------

if [ !${1+NODE_ROTATION} ]
then
    if [ -z "${IP_CHANGE_SECONDS}" ]; then IP_CHANGE_SECONDS=60; fi
fi

# Send the Tor process a HUP signal periodically. This will cause it to get a fresh exit IP address.
#
(while [${NODE_ROTATION} -eq 1]; do sleep ${IP_CHANGE_SECONDS}; echo "`date +'%Y/%m/%d %H:%M:%S'` 🔁 HUP → Tor."; killall -HUP tor; done) &

# ---------------------------------------------------------------------------------------------------------------------

exit_node_ip () {
    wget -q -Y on http://httpbin.org/ip -O - 2>/dev/null | grep origin | sed 's/"//g;s/  origin: //'
}

# Get current exit node IP address.
#
(while true; do sleep 60; echo "`date +'%Y/%m/%d %H:%M:%S'` 📌 exit IP: $(exit_node_ip)."; done) &

# ---------------------------------------------------------------------------------------------------------------------

# Options:
#
# - syslog
# - stdout
#
if [ -n "${LOG_NOTICE_TARGET}" ]
then
    sed -i 's/^\(Log notice\) syslog/\1 '$LOG_NOTICE_TARGET'/' $TORRC
fi

cat $TORRC

# ---------------------------------------------------------------------------------------------------------------------

exec /bin/su -s /bin/sh -c "/usr/bin/tor -f $TORRC" tor
