name: Build Docker Image
on: [push]
jobs:
  GitHub-Image-Builder:
    runs-on: ubuntu-latest
    steps:
      - 
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - 
        run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - 
        name: Check out repository code
        uses: actions/checkout@v3
      - 
        name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: build application
        run: make build-full
      - 
        run: echo "This job's status is ${{ job.status }}."
      - 
        name: image tagging
        run: make prepush
      - 
        name: push image
        run: make push